# docker-compose.yml

version: '3'

services:
  web:
    build: .
    command: sleep infinity

    volumes:
      - ./app:/app
      - ./projects:/projects
      - ./data:/data
      - /mnt/c/Users/34692/Downloads/Animes:/anime
      - /mnt/c/Users/34692/Downloads/Music:/music
      - /mnt/c/Users/34692/Downloads/Series:/serie
    ports:
      - 8008:8000
      - 8501:8501
