# docker-compose.yml

version: '3'

services:
  web:
    build: .
    command: sleep infinity

    volumes:
      - ./app:/app
      - ./projects:/projects
      - ./data:/data
    ports:
      - 8008:8000
      - 8501:8501
